sonar.projectKey=SportZoom_frontend
sonar.organization=sportzoom

sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.typescript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8
